In [123]:
import numpy

def cal_pop_fitness(equation_inputs, pop):

    #calculating the fitness value of each solution in the current population.
    #the fitness function calculates the sum of products of weights and inputs.
    
    fitness = numpy.sum(pop*equation_inputs, axis = 1)
    return fitness

In [124]:
def select_mating_pool(pop, fitness, num_parents):
    #select the best individuals as parents 
    parents = numpy.empty((num_parents, pop.shape[1]))
    
    for parent_num in range(num_parents):
        max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        parents[parent_num, :] = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -9999999999
    return parents

In [125]:
def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size) #we just take the center of chromosome
    crossover_point = numpy.uint8(offspring_size[1]/2)
    #print(crossover_point)
    for k in range(offspring_size[0]): 
        #the first parent
        parent1_idx = k%parents.shape[0]
        #the second parent
        parent2_idx = (k+1)%parents.shape[0]
        #the new offspring will have the 1st half gene of the 1st parents
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        #the new offspring will have the 2nd half gene of the 2nd parents
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
        
    return offspring
        

In [126]:
def mutation(offspring_crossover):
    for idx in range(offspring_crossover.shape[0]):
        random_value = numpy.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
        return offspring_crossover
    

In [127]:
#inputs of the equation
equation_inputs = [4,-2,3.5,5,-11,-4.7]
#number of weights
num_weights = 6

In [128]:
sol_per_pop = 8

#defining the population size 
pop_size = (sol_per_pop, num_weights)

#creating the initial population

new_population = numpy.random.uniform(low = -4.0, high = 4.0, size = pop_size)

print(new_population)

[[ 1.20204347 -3.59738234  3.15377915  0.29912136  2.70204023  1.35101756]
 [-1.10800327 -1.70196015  2.41352749 -1.72036083  0.1611162  -0.88799847]
 [ 1.21724817  0.03490626  1.82208081 -2.15732058 -2.02196398 -0.77983741]
 [-3.74419222  1.15013563 -3.1873158   1.21376163 -0.27513499 -0.26713443]
 [-1.61482292  3.71633349 -2.98128662  0.01016106  2.69713175  1.06844275]
 [-1.81560728  0.02941739 -0.01892405  1.40216256 -3.8444566   0.50839246]
 [ 2.83217764 -2.14485272 -1.00372071 -1.52656416  3.35880406 -1.97381698]
 [ 2.11820034  2.20901301  2.43708203  0.47482604 -1.73791569  0.39107425]]


In [129]:
#fitness = cal_pop_fitness(equation_inputs, new_population)
#print("fitness", fitness)
#parents = select_mating_pool(new_population, fitness, 4)
#print("parents", parents)
#offspring_crossover = crossover(parents,(4, 6))
#print("offspring crossover", offspring_crossover)

In [130]:
num_generations = 10

num_parents_mating = 4


for generation in range(num_generations):
    print("Generation : ", generation)
    fitness = cal_pop_fitness(equation_inputs, new_population) #calculating fitness
    #print(fitness)
    parents = select_mating_pool(new_population, fitness, num_parents_mating)
    #print("parents", generation)
    #print(parents)
    #using crossover to generate next generation
    offspring_crossover = crossover(parents,offspring_size=(pop_size[0]-parents.shape[0], num_weights))
    #print("the", generation,"offsprings :")
    #print(offspring_crossover)
    
    #using mutation to add some variations 
    offspring_mutation = mutation(offspring_crossover)
    #creating new population
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring_mutation
    #print(new_population)
    print("Best result: ", numpy.max(numpy.sum(new_population*equation_inputs, axis=1)))
fitness = cal_pop_fitness(equation_inputs, new_population)

best_match_idx = numpy.where(fitness == numpy.max(fitness))

print("Best solution : ", new_population[best_match_idx, :])
print("Best solution fitness : ", fitness[best_match_idx])

Generation :  0
Best result:  54.329644300447775
Generation :  1
Best result:  59.4949533369726
Generation :  2
Best result:  70.27355363113897
Generation :  3
Best result:  70.27355363113897
Generation :  4
Best result:  70.27355363113897
Generation :  5
Best result:  72.66930586509822
Generation :  6
Best result:  72.66930586509822
Generation :  7
Best result:  75.40305578463122
Generation :  8
Best result:  75.88438005788716
Generation :  9
Best result:  80.86986920738254
Best solution :  [[[ 2.11820034  2.20901301  2.43708203  1.40216256 -5.78763077
    0.50839246]]]
Best solution fitness :  [80.86986921]
