In [2]:
import numpy as np
from CNN_Model_Function import model

In [3]:
#def pop_gen(pop_size):
    pop_size = 2
    conv1_channel = np.random.randint(low = 2, high = 67, size = pop_size) 
    conv1_ksize = np.random.randint(low = 2, high = 11, size = pop_size)
    conv2_channel = np.random.randint(low = 32, high = 129, size = pop_size)
    conv2_ksize = np.random.randint(low = 2, high = 11, size = pop_size)
    pool_size = 2*np.random.randint(low = 2, high = 5, size = pop_size)
    drop_rate1 = np.random.uniform(low = 0.1, high = 0.9, size = pop_size)
    drop_rate2 = np.random.uniform(low = 0.1, high = 0.9, size = pop_size)
    FC_size = np.random.randint(low = 64, high = 257, size = pop_size)
    #batch_size = np.random.randint(low = 1, high = 257, size = pop_size)
    
    pop_matrix = np.array([conv1_channel,conv1_ksize,conv2_channel,conv2_ksize,\
                         pool_size,FC_size,drop_rate1,drop_rate2])
    pop_matrix = pop_matrix.T
    print(pop_matrix)
    print(pop_matrix.shape)
    #return pop_matrix

[[ 48.           5.         100.           7.           6.
  120.           0.47181075   0.53094545]
 [ 40.           7.         114.           6.           6.
  150.           0.41908622   0.59148427]]
(2, 8)


In [8]:
pop_matrix = offspring_crossover
print(pop_matrix)

[[ 46.           1.          78.           3.           8.
  151.           0.43301636   0.29174639]
 [ 38.           7.         128.           8.           8.
  137.           0.8495885    0.55845249]]


In [8]:
#def cal_fitness(pop_matrix, pop_size):
    fitness = np.zeros(pop_size)
    #print(fitness)
    score = np.zeros((pop_size, 2))
    #print(score)
    test_equ = np.random.randn(8)
    for i in range(pop_size):
        gafit = model(pop_matrix[i,0],pop_matrix[i,1],pop_matrix[i,2],pop_matrix[i,3],pop_matrix[i,4],pop_matrix[i,5],pop_matrix[i,6],pop_matrix[i,7])
        fitness[i] = gafit[0]
        score[i,:] = gafit[1]
    print(fitness,score)
    #return fitness 

Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 483s 8ms/step - loss: 0.3539 - acc: 0.8872 - val_loss: 0.0616 - val_acc: 0.9792
Epoch 2/3
60000/60000 [==============================] - 462s 8ms/step - loss: 0.1353 - acc: 0.9607 - val_loss: 0.0396 - val_acc: 0.9862
Epoch 3/3
60000/60000 [==============================] - 451s 8ms/step - loss: 0.1061 - acc: 0.9685 - val_loss: 0.0326 - val_acc: 0.9893
Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 296s 5ms/step - loss: 0.4986 - acc: 0.8407 - val_loss: 0.0962 - val_acc: 0.9712
Epoch 2/3
60000/60000 [==============================] - 295s 5ms/step - loss: 0.2015 - acc: 0.9404 - val_loss: 0.0855 - val_acc: 0.9731
Epoch 3/3
60000/60000 [==============================] - 302s 5ms/step - loss: 0.1666 - acc: 0.9521 - val_loss: 0.0663 - val_acc: 0.9797
[0.95666042 0.91337072] [[0.03263958 0.9893    ]
 [0.06632928 0.9797    ]]


In [5]:
#def select_parents(pop_matrix, fitness, num_parents):
    fitness = [5,2,3,6]
    pop_matrix = np.array([[1,1,2,2,4,6,3,5],[2,2,3,3,4,6,7,8],[3,3,4,4,8,9,6,3],[4,4,5,5,2,2,3,4]])
    num_parents = 4
    parents = np.empty((num_parents, pop_matrix.shape[1]))
    for i in range(num_parents):
        max_idx = np.where(fitness == np.max(fitness))
        print(max_idx)
        max_idx = max_idx[0][0]
        print(max_idx)
        parents[i, :] = pop_matrix[max_idx, :]
        fitness[max_idx] = -99999999999
    #return parents
    print(parents)

(array([3]),)
3
(array([0]),)
0
(array([2]),)
2
(array([1]),)
1
[[4. 4. 5. 5. 2. 2. 3. 4.]
 [1. 1. 2. 2. 4. 6. 3. 5.]
 [3. 3. 4. 4. 8. 9. 6. 3.]
 [2. 2. 3. 3. 4. 6. 7. 8.]]


In [78]:
#def crossover(parents, offspring_size):
    offspring_size = (4,8)
    offspring = np.empty(offspring_size)
    crossover_pt = np.uint8(offspring_size[1]/2)
    for k in range(offspring_size[0]):
        parent1_idx = k%parents.shape[0]
        parent2_idx = (k+1)%parents.shape[0]
        offspring[k, 0:crossover_pt] = parents[parent1_idx, 0:crossover_pt]
        offspring[k, crossover_pt:] = parents[parent2_idx, crossover_pt:]
    #return offspring
    print(offspring)   

[[4. 4. 5. 5. 4. 6. 3. 5.]
 [1. 1. 2. 2. 8. 9. 6. 3.]
 [3. 3. 4. 4. 4. 6. 7. 8.]
 [2. 2. 3. 3. 2. 2. 3. 4.]]


In [79]:
#def mutation(offspring_crossover):
    offspring_crossover = offspring
    #random_idx = np.random.randint(low = 0, high = 5, size = 1)
    #print(random_idx)
    for j in range(offspring_crossover.shape[0]):
        random_idx = np.random.randint(low = 0, high = 6, size = 1)
        random_value = np.random.randint(low = -1, high = 1 , size=1)                        
        offspring_crossover[j, random_idx] = offspring_crossover[j, random_idx] + random_value
    #return offspring_crossover
    print(offspring_crossover)

[[4. 4. 5. 5. 4. 6. 3. 5.]
 [1. 1. 2. 2. 8. 9. 6. 3.]
 [2. 3. 4. 4. 4. 6. 7. 8.]
 [2. 2. 3. 3. 2. 1. 3. 4.]]


In [71]:
random_idx = np.random.randint(low = 0, high = 6, size = 1)
print(random_idx)

[5]
