In [23]:
import numpy as np
from CNN_Model_Function import model

In [24]:

pop_size = 4
#generate random number for each hyperparameter with given distribution
conv1_channel = np.random.randint(low = 1, high = 129, size = pop_size) 
conv1_ksize = np.random.randint(low = 1, high = 9, size = pop_size)
conv2_channel = np.random.randint(low = 1, high = 129, size = pop_size)
conv2_ksize = np.random.randint(low = 1, high = 9, size = pop_size)
pool_size = 2*np.random.randint(low = 1, high = 5, size = pop_size)
drop_rate1 = np.random.uniform(low = 0.2, high = 0.6, size = pop_size)
drop_rate2 = np.random.uniform(low = 0.2, high = 0.6, size = pop_size)
FC_size = np.random.randint(low = 32, high = 513, size = pop_size)
batch_size = 2**np.random.randint(low = 4, high = 9, size = pop_size)
#epoch = np.random.randint(low = 5, high = 21, size = pop_size)

In [25]:
#print(conv1_channel)
#print(conv1_ksize)
#print(conv2_channel)
#print(conv2_ksize)
#print(pool_size)
#print(drop_rate1)
#print(FC_size)
#print(batch_size.shape)
#print(epoch)
#conv1_channel.dtype

In [26]:
pop_matrix=np.array([conv1_channel,conv1_ksize,conv2_channel,conv2_ksize,pool_size,drop_rate1,drop_rate2,FC_size,batch_size])

In [27]:
#pop_matrix = np.vstack((conv1_channel, conv1_ksize, conv2_channel, conv2_ksize,
                        #pool_size, drop_rate1, drop_rate2, batch_size, FC_size))

In [28]:
print(pop_matrix)
print(pop_matrix.shape)

[[9.80000000e+01 2.00000000e+00 2.90000000e+01 9.40000000e+01]
 [3.00000000e+00 5.00000000e+00 7.00000000e+00 8.00000000e+00]
 [1.27000000e+02 1.40000000e+01 6.00000000e+00 1.14000000e+02]
 [6.00000000e+00 8.00000000e+00 5.00000000e+00 2.00000000e+00]
 [4.00000000e+00 4.00000000e+00 8.00000000e+00 6.00000000e+00]
 [5.45369538e-01 5.97632443e-01 5.60429838e-01 4.02231156e-01]
 [3.77269063e-01 4.72563415e-01 4.05761738e-01 2.11059638e-01]
 [2.25000000e+02 2.26000000e+02 3.28000000e+02 4.53000000e+02]
 [3.20000000e+01 1.60000000e+01 1.28000000e+02 3.20000000e+01]]
(9, 4)


In [29]:
pop_matrix = pop_matrix.T

pop_matrix.dtype


dtype('float64')

In [30]:
print(pop_matrix)
print(pop_matrix.shape)


[[9.80000000e+01 3.00000000e+00 1.27000000e+02 6.00000000e+00
  4.00000000e+00 5.45369538e-01 3.77269063e-01 2.25000000e+02
  3.20000000e+01]
 [2.00000000e+00 5.00000000e+00 1.40000000e+01 8.00000000e+00
  4.00000000e+00 5.97632443e-01 4.72563415e-01 2.26000000e+02
  1.60000000e+01]
 [2.90000000e+01 7.00000000e+00 6.00000000e+00 5.00000000e+00
  8.00000000e+00 5.60429838e-01 4.05761738e-01 3.28000000e+02
  1.28000000e+02]
 [9.40000000e+01 8.00000000e+00 1.14000000e+02 2.00000000e+00
  6.00000000e+00 4.02231156e-01 2.11059638e-01 4.53000000e+02
  3.20000000e+01]]
(4, 9)


In [ ]:
#Here we test the CNN model

#for i in range(0,pop_size):
    score, model_log = model(pop_matrix[0,0],pop_matrix[0,1],pop_matrix[0,2],pop_matrix[0,3],pop_matrix[0,4],pop_matrix[0,5],pop_matrix[0,6],pop_matrix[0,7],pop_matrix[0,8])
    print('Test Loss:', score[0])
    print('Test accuracy:', score[1])



Train on 60000 samples, validate on 10000 samples
Epoch 1/10
36480/60000 [=================>............] - ETA: 7:21 - loss: 0.2040 - acc: 0.9362