In [2]:
import numpy as np
from CNN_Model_Function import model

In [3]:

pop_size = 3
#generate random number for each hyperparameter with given distribution
conv1_channel = np.random.randint(low = 1, high = 129, size = pop_size) 
conv1_ksize = np.random.randint(low = 1, high = 9, size = pop_size)
conv2_channel = np.random.randint(low = 1, high = 129, size = pop_size)
conv2_ksize = np.random.randint(low = 1, high = 9, size = pop_size)
pool_size = 2*np.random.randint(low = 1, high = 5, size = pop_size)
drop_rate1 = np.random.uniform(low = 0.2, high = 0.6, size = pop_size)
drop_rate2 = np.random.uniform(low = 0.2, high = 0.6, size = pop_size)
FC_size = np.random.randint(low = 32, high = 513, size = pop_size)
#batch_size = 2**np.random.randint(low = 4, high = 9, size = pop_size)
#epoch = np.random.randint(low = 5, high = 21, size = pop_size)

In [4]:
#print(conv1_channel)
#print(conv1_ksize)
#print(conv2_channel)
#print(conv2_ksize)
#print(pool_size)
#print(drop_rate1)
#print(FC_size)
#print(batch_size.shape)
#print(epoch)
#conv1_channel.dtype

In [5]:
pop_matrix=np.array([conv1_channel,conv1_ksize,conv2_channel,conv2_ksize,pool_size,drop_rate1,drop_rate2,FC_size])

In [6]:
#pop_matrix = np.vstack((conv1_channel, conv1_ksize, conv2_channel, conv2_ksize,
                        #pool_size, drop_rate1, drop_rate2, batch_size, FC_size))

In [7]:
print(pop_matrix)
print(pop_matrix.shape)

[[8.30000000e+01 1.28000000e+02 9.90000000e+01]
 [5.00000000e+00 6.00000000e+00 5.00000000e+00]
 [7.80000000e+01 1.28000000e+02 2.50000000e+01]
 [7.00000000e+00 6.00000000e+00 7.00000000e+00]
 [8.00000000e+00 6.00000000e+00 8.00000000e+00]
 [5.37858295e-01 2.33922090e-01 3.53512185e-01]
 [2.06369435e-01 3.48254144e-01 3.65607223e-01]
 [3.99000000e+02 4.40000000e+01 1.89000000e+02]]
(8, 3)


In [8]:
pop_matrix = pop_matrix.T

pop_matrix.dtype


dtype('float64')

In [9]:
print(pop_matrix)
print(pop_matrix.shape)


[[8.30000000e+01 5.00000000e+00 7.80000000e+01 7.00000000e+00
  8.00000000e+00 5.37858295e-01 2.06369435e-01 3.99000000e+02]
 [1.28000000e+02 6.00000000e+00 1.28000000e+02 6.00000000e+00
  6.00000000e+00 2.33922090e-01 3.48254144e-01 4.40000000e+01]
 [9.90000000e+01 5.00000000e+00 2.50000000e+01 7.00000000e+00
  8.00000000e+00 3.53512185e-01 3.65607223e-01 1.89000000e+02]]
(3, 8)


In [10]:
#Here we test the CNN model

#for i in range(0,pop_size):
    gafit = model(pop_matrix[0,0],pop_matrix[0,1],pop_matrix[0,2],pop_matrix[0,3],pop_matrix[0,4],pop_matrix[0,5],pop_matrix[0,6],pop_matrix[0,7])
    print(gafit)
    



IndexError: index 8 is out of bounds for axis 1 with size 8

In [11]:
print(gafit)

([0.04792721611284069, 0.9846], <keras.callbacks.History object at 0x127155b70>, 0.9366727838871594)
